development:
  adapter: postgresql
  encoding: unicode
  database: blogger_development
  pool: 5
  username: blogger
  password: blogger
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: blogger_test
  pool: 5
  username: blogger
  password: blogger
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
